--GROUP BY--

-- O GROUP BY BASICAMENTE DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS
--PARA CADA GRUPO VOCE PODE APLICAR UMA FUNÇÃO DE AGREGAÇÃO, POR EXEMPLO:
--CALCULAR A SOMA DE ITENS 
--CONTAR O NUMERO DE ITENS NAQUELE GRUPO

--SELECT COLUNA1,FUNÇAOAGREGAÇAO(COLUNA2)
--FROM NOMETABELA
--GROUP BY COLUNA1

SELECT *
FROM Sales.SalesOrderDetail

SELECT SpecialOfferID, SUM(UnitPrice) AS "SOMA"
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID

SELECT ProductId, COUNT(ProductId) AS "CONTAGEM"
FROM Sales.SalesOrderDetail
GROUP BY ProductID

--VAMOS DIZER QUE EU QUERO SABER QUANTOS NOMES DE CADA NOME TEMOS CADASTRADOS
--EM NOSSO BANCO DE DADOS

SELECT FirstName, COUNT(FirstName) AS "CONTAGEM"
FROM Person.Person
GROUP BY FirstName

--NA TABELA PRODUCTION.PRODUCT EU QUERO SABER A MEDIA DE PREÇO PARA OS PRODUTOS
--QUE SÃO PRATAS(SILVER)

SELECT Color,AVG(ListPrice) "PREÇO"
FROM Production.Product
WHERE Color = 'SILVER'
GROUP BY Color

--DESAFIO 01--

/* EU PRECISO SABER QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR
MIDDLENAME */

SELECT MiddleName, COUNT(MiddleName) AS "QUANTIDADE"
FROM Person.Person
GROUP BY MiddleName

--DESAFIO 02--

/* EU PRECISO SABER EM MEDIA QUAL A QUANTIDADE QUE CADA PRODUTO É VENDIDO NA LOJA. */

SELECT ProductId,AVG(OrderQty) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID

--DESAFIO 03--

/* EU QUERO SABER QUAIS FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE
VENDA(LINE TOTAL) POR PRODUTO DO MAIOR PARA O MENOR */

SELECT TOP 10 PRODUCTID, SUM(LINETOTAL)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal)DESC;

--DESAFIO 04--

/* EU PRECISO SABER QUANTOS PRODUTOS E QUAL A QUANTIDADE MEDIA DE PRODUTOS TEMOS
CADASTRADOS NAS NOSSAS ORDENS DE SERVIÇO(WORKORDER), AGRUPADOS POR PRODUCTID */

SELECT PRODUCTID, COUNT(ProductID) "CONTAGEM",
AVG(OrderQty) "MEDIA"
FROM Production.WorkOrder
GROUP BY ProductID