--BETWEEN--

-- O BETWEEN É USADO PARA ENCONTRAR UM VALOR MÍNIMO E VALOR MÁXIMO
-- VALOR BETWEEN MÍNIMO AND MÁXIMO;
-- É A MESMA COISA QUE DIZER:
-- VALOR >= MÍNIMO AND VALOR <= MÁXIMO;

SELECT *
FROM
Production.Product
WHERE ListPrice BETWEEN 1000 AND 1500;

SELECT *
FROM Production.Product
WHERE ListPrice NOT BETWEEN 1000 AND 1500; -- LISTA VALORES QUE NÃO ESTÃO ENTRE 1000 E 1500 --

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01'
ORDER BY HireDate