--MIN MAX SUM AVG--

/* FUNÇÕES DE AGREGAÇÃO BASICAMENTE AGREGAM OU COMBINAM DADOS DE UMA TABELA 
EM UM RESULTADO SÓ */

--SUM CALCULA O TOTAL DE DETERMINADA COLUNA--
SELECT  TOP 10 SUM(LineTotal) AS "SOMA"  -- 'AS' NOMEIA UMA COLUNA --
FROM Sales.SalesOrderDetail

--MIN CALCULA O MENOR VALOR TOTAL--
SELECT TOP 10 MIN(LineTotal)
FROM Sales.SalesOrderDetail

--MAX CALCULA O VALOR MÁXIMO CADASTRADO DO TOTAL--
SELECT TOP 10 MAX(LineTotal)
FROM Sales.SalesOrderDetail

--AVG CALCULA A MEDIA DO VALOR TOTAL CADASTRADO--
SELECT TOP 10 AVG(LineTotal)
FROM Sales.SalesOrderDetail