--COUNT--

--SELECT COUNT(DISTINCT coluna1)
--FROM TABELA

SELECT COUNT (Title)
FROM Person.Person

--DESAFIO 01--

/* EU QUERO SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS
(PRODUCTION.PRODUCT) */

SELECT COUNT(ProductNumber)
FROM Production.Product

--DESAFIO 02--

/* EU QUERO SABER QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA
(PRODUCTION.PRODUCT) */

SELECT COUNT( Size)
FROM Production.Product

--DESAFIO 03--

/* EU QUERO SABER QUANTOS TAMANHOS DIFERENTES DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA
(PRODUCTION.PRODUCT) */

SELECT COUNT(DISTINCT Size)
FROM Production.Product

--TOP--

--SELECT TOP 10 *
--FROM TABELA

SELECT TOP 10 *
FROM Production.Product

